### PR TITLE
window: save column widths on shutdown (fixes #290)

### LINKED ISSUE #290: "remember column configuration" does not work column width
"remember column configuration" does not work for column width

**To Reproduce**
1. Edit > Preference > interface tab > check "remember column configuration"
2. open the application and increase the width of "path" column 
3. close the application then search again and the "path" column width is reset to its defaults

**Expected behavior**
preserve the width configuration of columns

**Version**
 - installed FSearch from: PPA - stable
 - Version: `FSearch 0.1`

### PR DESCRIPTION
**Pull request by mrubli**
I couldn't find an `ARRAY_SIZE()` macro or anything similar. Please let me know if I've missed something. Also feel free to directly change anything that doesn't match your code style preference.

### CODE REVIEW

File: src/fsearch_window.c [hunk 1]
```diff
@@ -1221,6 +1221,23 @@ fsearch_application_window_prepare_shutdown(gpointer self) {
...
+        // update the config with the widths of all columns whose width we can store
+        const struct { int type; uint32_t *width; } columns[] = {
+            { DATABASE_INDEX_TYPE_NAME,              &config->name_column_width      },
+            { DATABASE_INDEX_TYPE_PATH,              &config->path_column_width      },
+            { DATABASE_INDEX_TYPE_FILETYPE,          &config->type_column_width      },
+            { DATABASE_INDEX_TYPE_EXTENSION,         &config->extension_column_width },
+            { DATABASE_INDEX_TYPE_SIZE,              &config->size_column_width      },
+            { DATABASE_INDEX_TYPE_MODIFICATION_TIME, &config->modified_column_width  },
+        };
+        for (int i = 0; i < sizeof(columns) / sizeof(columns[0]); i++) {
```
Comment (cboxdoerfer) [inline src/fsearch_window.c:1234]: Glib provides the `G_N_ELEMENTS`macro which you can use here for the number of array elements.

**Review by cboxdoerfer — CHANGES_REQUESTED** [review]

File: src/fsearch_window.c (hunk 1 above)
Comment (mrubli) [reply src/fsearch_window.c]: Thanks, I knew there had to be something. I pushed the updated branch.

**Comment by cboxdoerfer** [comment]
Thank you!
